sonar.projectKey=TobiasPummer_cd-mcm-exercise-Pummer
sonar.organization=tobiaspummer

sonar.projectName=cd-mcm-exercise-Pummer
sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out

sonar.sourceEncoding=UTF-8