sonar.projectKey=TobiasPummer_cd-mcm-exercise-Pummer
sonar.organization=tobiaspummer

sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,.github/**,k8s/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out

sonar.sourceEncoding=UTF-8
